export const ASSIGNMENT_STATES = {
  NO_ASSIGNMENT: 'NO_ASSIGNMENT',
  ASSIGNMENT_REVEALED: 'ASSIGNMENT_REVEALED',
  IS_REVEALING: 'IS_REVEALING',
  ASSIGNMENT_HIDDEN: 'ASSIGNMENT_HIDDEN',
} as const;

export type AssignmentState = typeof ASSIGNMENT_STATES[keyof typeof ASSIGNMENT_STATES];
